# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 2.1.7
_src_path: gh:algorandfoundation/algokit-fullstack-template
author_email: yopisaputra9@gmail.com
author_name: yopisaputra
contract_name: sertifikat_kompetensi
deployment_language: python
preset_name: starter
project_name: sertifikat_kompetensi

